---
title: kinetic
timezone: UTC
description:
#url: ""
url: "http://127.0.0.1:4000"
keywords:
markdown: kramdown
layout: default
plugins:
- jekyll-menus
collections:
  careers:
    output: true
defaults:
- scope:
    path: ''
    type: careers
  values:
    layout: career
    permalink: "/career/:title"
- scope:
    path: ''
    type: posts
  values:
    layout: blog
    permalink: "/blog/:year/:month/:day/"
